spin_manifest_version = "1"
authors = ["Till Schneidereit <till@tillschneidereit.net>"]
description = ""
name = "tst"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = ""
source = "target/comp.wasm"
allowed_http_hosts = ["https://random-data-api.fermyon.app/"]
key_value_stores = ["default"]
[component.trigger]
route = "/..."
[component.config]
test = "https://my-api.com"
[component.build]
command = "npx rollup -c && mkdir -p target && npx jco componentize -w ./node_modules/spin-sdk/wit -o target/comp.wasm -n http-trigger dist/bundle.js"
